version: "3"
services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    image: school_management_app
    volumes:
      - ./app:/var/www/html
    working_dir: /var/www/html
    user: "www-data"
    depends_on:
      - db
  nginx:
    image: nginx:stable-alpine
    ports:
      - "8080:80"
    volumes:
      - ./app:/var/www/html
      - ./.docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - web
  db:
    image: mariadb:latest
    environment:
      MARIADB_USER: school_user
      MARIADB_PASSWORD: secret
      MARIADB_ROOT_PASSWORD: secret
      MARIADB_DATABASE: school_management
    ports:
      - "3306:3306"
    volumes:
      - dbdata:/var/lib/mysql
      - mysql_backups:/backups
  phpmyadmin:
    image: phpmyadmin/phpmyadmin:latest
    environment:
      PMA_HOST: db
      PMA_PORT: 3306
      PMA_USER: root
      PMA_PASSWORD: secret

    ports:
      - "8081:80"
    depends_on:
      - db

volumes:
  dbdata:
  mysql_backups:

