<?php

namespace Tests\Feature;

use App\Models\classes;
use App\Models\ClassRoom;
use App\Models\Grade;
use App\Models\Job;
use App\Models\schedules;
use App\Models\User;
use Illuminate\Foundation\Testing\RefreshDatabase;
use Illuminate\Support\Facades\DB;
use Livewire\Livewire;
use Mcamara\LaravelLocalization\Middleware\LaravelLocalizationRedirectFilter;
use Mcamara\LaravelLocalization\Middleware\LocaleSessionRedirect;
use Spatie\Permission\Models\Permission;
use Tests\TestCase;

class ScheduleEnhancementTest extends TestCase
{
    use RefreshDatabase;

    protected function setUp(): void
    {
        parent::setUp();

        DB::table('schools')->insert([
            'id' => 1,
            'name' => 'Test School',
            'phone' => '1234567890',
            'address' => 'Test Address',
        ]);

        Permission::create(['name' => 'scheduale-list', 'guard_name' => 'web']);
    }

    protected function createTeacher(array $overrides = []): User
    {
        $job = Job::factory()->create();
        $teacher = User::factory()->create(array_merge([
            'type' => 'teacher',
            'job_id' => $job->id,
            'lesson_count' => 4,
            'school_id' => 1,
        ], $overrides));

        $teacher->givePermissionTo('scheduale-list');

        return $teacher;
    }

    protected function createClass(Grade $grade): classes
    {
        $classRoom = ClassRoom::factory()->create();

        return classes::create([
            'title' => 'Class '.$grade->id.'-'.rand(1, 10),
            'grade_id' => $grade->id,
            'class_room_id' => $classRoom->id,
            'school_id' => 1,
            'user_id' => 1,
        ]);
    }

    protected function createGrade(): Grade
    {
        $user = User::factory()->create();

        return Grade::create([
            'name' => 'Test Grade '.rand(1, 100),
            'user_id' => $user->id,
            'slug' => 'test-grade-'.rand(1, 100),
            'school_id' => 1,
        ]);
    }

    public function test_auto_generate_clears_existing_entries(): void
    {
        $grade = $this->createGrade();
        $teacher = $this->createTeacher();
        $teacher->grades()->attach($grade->id, ['school_id' => 1]);
        $class = $this->createClass($grade);

        // Create old entries that would never be regenerated by autoGenerate
        // (friday is not in the auto-generate days list)
        schedules::create([
            'user_id' => $teacher->id,
            'class_id' => $class->id,
            'job_id' => $teacher->job_id,
            'day' => 'friday',
            'period' => '1',
        ]);

        $this->assertDatabaseCount('schedules', 1);

        Livewire::test(\App\Livewire\Schedules::class)
            ->call('autoGenerate');

        // autoGenerate clears old entries (soft delete) and creates fresh schedules
        $this->assertSoftDeleted('schedules', [
            'day' => 'friday',
        ]);
        $this->assertGreaterThan(0, schedules::withTrashed()->count());
    }

    public function test_auto_generate_distributes_across_days(): void
    {
        $grade = $this->createGrade();
        $teacher = $this->createTeacher(['lesson_count' => 6]);
        $teacher->grades()->attach($grade->id, ['school_id' => 1]);
        $class = $this->createClass($grade);

        Livewire::test(\App\Livewire\Schedules::class)
            ->call('autoGenerate');

        $schedules = schedules::where('user_id', $teacher->id)->get();
        $days = $schedules->pluck('day')->unique();

        $this->assertGreaterThanOrEqual(4, $days->count());
    }

    public function test_auto_generate_respects_lesson_count(): void
    {
        $grade = $this->createGrade();
        $teacher = $this->createTeacher(['lesson_count' => 4]);
        $teacher->grades()->attach($grade->id, ['school_id' => 1]);
        $class = $this->createClass($grade);

        Livewire::test(\App\Livewire\Schedules::class)
            ->call('autoGenerate');

        $count = schedules::where('user_id', $teacher->id)->count();
        $this->assertEquals(4, $count);
    }

    public function test_auto_generate_no_teacher_conflicts(): void
    {
        $grade = $this->createGrade();
        $teacher = $this->createTeacher(['lesson_count' => 8]);
        $teacher->grades()->attach($grade->id, ['school_id' => 1]);
        $class = $this->createClass($grade);

        Livewire::test(\App\Livewire\Schedules::class)
            ->call('autoGenerate');

        $conflicts = schedules::query()
            ->selectRaw('user_id, day, period, count(*) as cnt')
            ->groupBy('user_id', 'day', 'period')
            ->having('cnt', '>', 1)
            ->count();

        $this->assertEquals(0, $conflicts);
    }

    public function test_auto_generate_no_class_conflicts(): void
    {
        $grade = $this->createGrade();
        $teacher1 = $this->createTeacher(['lesson_count' => 4]);
        $teacher2 = $this->createTeacher(['lesson_count' => 4]);
        $teacher1->grades()->attach($grade->id, ['school_id' => 1]);
        $teacher2->grades()->attach($grade->id, ['school_id' => 1]);
        $class = $this->createClass($grade);

        Livewire::test(\App\Livewire\Schedules::class)
            ->call('autoGenerate');

        $conflicts = schedules::query()
            ->selectRaw('class_id, day, period, count(*) as cnt')
            ->groupBy('class_id', 'day', 'period')
            ->having('cnt', '>', 1)
            ->count();

        $this->assertEquals(0, $conflicts);
    }

    public function test_auto_generate_skips_teacher_without_grades(): void
    {
        $teacher = $this->createTeacher(['lesson_count' => 4]);

        Livewire::test(\App\Livewire\Schedules::class)
            ->call('autoGenerate');

        $count = schedules::where('user_id', $teacher->id)->count();
        $this->assertEquals(0, $count);
    }

    public function test_teacher_print_route_returns_view(): void
    {
        $this->withoutMiddleware([
            LocaleSessionRedirect::class,
            LaravelLocalizationRedirectFilter::class,
        ]);

        $teacher = $this->createTeacher();
        $this->actingAs($teacher);

        $response = $this->get(route('schedule.print.teacher', $teacher->id));

        $response->assertStatus(200);
    }

    public function test_classroom_print_route_returns_view(): void
    {
        $this->withoutMiddleware([
            LocaleSessionRedirect::class,
            LaravelLocalizationRedirectFilter::class,
        ]);

        $teacher = $this->createTeacher();
        $this->actingAs($teacher);

        $grade = $this->createGrade();
        $class = $this->createClass($grade);

        $response = $this->get(route('schedule.print.classroom', $class->id));

        $response->assertStatus(200);
    }

    public function test_grade_print_route_returns_view(): void
    {
        $this->withoutMiddleware([
            LocaleSessionRedirect::class,
            LaravelLocalizationRedirectFilter::class,
        ]);

        $teacher = $this->createTeacher();
        $this->actingAs($teacher);

        $grade = $this->createGrade();

        $response = $this->get(route('schedule.print.grade', $grade->id));

        $response->assertStatus(200);
    }

    public function test_teacher_print_view_contains_table_structure(): void
    {
        $this->withoutMiddleware([
            LocaleSessionRedirect::class,
            LaravelLocalizationRedirectFilter::class,
        ]);

        $teacher = $this->createTeacher();
        $this->actingAs($teacher);

        $response = $this->get(route('schedule.print.teacher', $teacher->id));

        $response->assertSee('window.print()');
        $response->assertSeeText('جدول المدرس');
    }

    public function test_classroom_print_view_contains_table_structure(): void
    {
        $this->withoutMiddleware([
            LocaleSessionRedirect::class,
            LaravelLocalizationRedirectFilter::class,
        ]);

        $teacher = $this->createTeacher();
        $this->actingAs($teacher);

        $grade = $this->createGrade();
        $class = $this->createClass($grade);

        $response = $this->get(route('schedule.print.classroom', $class->id));

        $response->assertSee('window.print()');
        $response->assertSeeText('جدول الفصل');
    }

    public function test_grade_print_view_contains_table_structure(): void
    {
        $this->withoutMiddleware([
            LocaleSessionRedirect::class,
            LaravelLocalizationRedirectFilter::class,
        ]);

        $teacher = $this->createTeacher();
        $this->actingAs($teacher);

        $grade = $this->createGrade();

        $response = $this->get(route('schedule.print.grade', $grade->id));

        $response->assertSee('window.print()');
        $response->assertSeeText('جدول المرحلة');
    }
}
